require("kobold_survival")

function Precache(context)
    PrecacheUnitByNameSync("npc_dota_hero_kobold_survivor", context)
    PrecacheUnitByNameSync("npc_kobold_building_campfire", context)
    PrecacheUnitByNameSync("npc_kobold_building_tent", context)
    PrecacheUnitByNameSync("npc_kobold_building_farm", context)
    PrecacheUnitByNameSync("npc_kobold_building_workbench", context)
    PrecacheUnitByNameSync("npc_kobold_building_smithy", context)
    PrecacheUnitByNameSync("npc_kobold_building_storage", context)
    PrecacheUnitByNameSync("npc_kobold_building_hunters_lodge", context)
    PrecacheUnitByNameSync("npc_kobold_building_tavern", context)
    PrecacheUnitByNameSync("npc_kobold_building_spike_trap", context)
    PrecacheUnitByNameSync("npc_kobold_building_revival_shrine", context)
    PrecacheUnitByNameSync("npc_kobold_node_ordinary_tree", context)
    PrecacheUnitByNameSync("npc_kobold_node_elder_tree", context)
    PrecacheUnitByNameSync("npc_kobold_node_stone_deposit", context)
    PrecacheUnitByNameSync("npc_kobold_node_gold_deposit", context)
    PrecacheUnitByNameSync("npc_kobold_node_iron_deposit", context)
    PrecacheUnitByNameSync("npc_kobold_node_shadowstone_source", context)
    PrecacheUnitByNameSync("npc_kobold_node_radiant_gemstone_source", context)
    PrecacheUnitByNameSync("npc_kobold_node_berry_bush", context)
    PrecacheUnitByNameSync("npc_kobold_node_spicy_herbs", context)
    PrecacheUnitByNameSync("npc_kobold_node_sageberry", context)
    PrecacheUnitByNameSync("npc_kobold_node_lambent_sunflower", context)
    PrecacheUnitByNameSync("npc_kobold_animal_sheep", context)
    PrecacheUnitByNameSync("npc_kobold_animal_pheasant", context)
    PrecacheUnitByNameSync("npc_kobold_animal_wolf", context)
    PrecacheUnitByNameSync("npc_kobold_animal_dire_wolf", context)
    PrecacheUnitByNameSync("npc_kobold_animal_bear", context)
    PrecacheUnitByNameSync("npc_kobold_animal_stag", context)
    PrecacheUnitByNameSync("npc_kobold_murloc_slave", context)
    PrecacheUnitByNameSync("npc_kobold_boss_raging_arcane_beast", context)
end

function Activate()
    GameRules.KoboldSurvival = KoboldSurvivalGameMode()
    GameRules.KoboldSurvival:InitGameMode()
end
